macro(AddExercise name sources)
    set(EX_TARGET ${name})
    message("${sources}")
    add_executable(${EX_TARGET} ${sources})
    target_compile_options(${EX_TARGET} PRIVATE -f elf64 -l ${EX_TARGET}.lst)

    set (extra_args ${ARGN})
    list(LENGTH extra_args extra_count)
    if(${extra_count} GREATER 0)
        list(GET extra_args 0 libs)
        target_link_libraries(${EX_TARGET} PRIVATE ${libs})
    endif()
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        message("Compile Debug version")
        target_compile_options(${EX_TARGET} PRIVATE -g -Fdwarf)
    endif()
endmacro()